### ISSUE TITLE
using spikes clips 

### ISSUE THREAD

**Issue by ferchaure** [flatironinstitute/ironclust#33]
Hi, Is it possible to use Ironclust in previously detected spikes?
Which should be the structure of the file with the spikes to do something like that?

**Comment by jamesjun** [comment]
it uses PC features for sorting (trFet_spk)  pope but I haven’t implemented an importing tool yet to extract features from spike clips. I think it should be easy and possible. Which format do you want to import from? Do you have an example file available to share?

-James

**Comment by ferchaure** [comment]
I'm testing a few things on single channels and for that cases I uses a matrix in a .mat. You can find an example file [here](https://drive.google.com/file/d/1UCWUzpNYsbNYTY6brhnIFeUjFbmqd-LA/view?usp=sharing). I know that the structure should be more complex for polytrodes, if you show me the easiest way to give spikes to ironclus I will do the conversion.

**Comment by jamesjun** [comment]
I added `irc2 import-clip myfile.mat` command. it will output [firings.mda](https://github.com/magland/mountainlab/blob/master/old/doc/mda_format.md)  file in the same directory where the .mat file is located. Please click on the link to learn how to parse the output.

**Comment by ferchaure** [comment]
Sorry I wasn't able to run the code, I though that I was doing something wrong. I tried a few things like adding a check in the line 116 of irc2 to don't enter the if when S0 already exist, etc;  but I couldn't fix the the real issue.
