### ISSUE TITLE
Traces

### ISSUE THREAD

**Issue by lorenzfenk** [flatironinstitute/ironclust#40]
Hello,
I am quite new to spike-sorting more generally and using ironclust in particular, repeatedly encountering the following issue when trying to sort my Neuropixels (3B staggered) recordings using ironclust (v5.0.5 (10/14/2019)): 
Clusters seem ok, peak amplitudes are detected at the right channels, and spike waveforms also look good (i.e. what to expect from inspecting the raw data). However, when I look at the traces (>> irc traces...) it is almost always regions outside the actual spikes that get labelled (and stored with the corresponding time stamps). In fact, even if I set the very threshold high, it is not big spikes that get labelled but these small wiggles instead.
I have attached an example for demonstration (qqFactor=5). In the overview you can see how the vast majority of spikes is missed in traces. In the second example – zooming in on channel 21 – not a single spike was correctly labelled in ‘traces’ over a period of 2min, yet the overlaid waveforms of ~100 spikes look just fine (and any wiggles/flat traces are absent)... 
I imagine if that was due to a bug it would have been noticed by many others before, so maybe doing something stupid, but would be grateful for your advice.
all the best!
lorenz

<img width="1529" alt="Screen Shot 2020-02-03 at 20 49 48" src="https://user-images.githubusercontent.com/60577994/73685626-c1603c80-46c6-11ea-8fdb-77def778ef75.png">

<img width="1673" alt="Screen Shot 2020-02-02 at 16 19 20" src="https://user-images.githubusercontent.com/60577994/73684005-9de7c280-46c3-11ea-99e2-94a1fbf021e5.png">

**Comment by jamesjun** [comment]
Thanks for reporting the error. I implemented `irc2 traces [myparam.prm]` command. Please see README.md for more details.

**Comment by lorenzfenk** [comment]
Dear James,
Thanks for your reply, I will test irc2 asap.
However, regarding the problem I have been having when running irc traces, I have followed up on that: The issue arises only when specifying a time range in “tlim_load”; ie if the field is empty or the time window starts with 0 it is all fine, but as soon as the time range doesn’t start with zero the problem occurs (e.g. [0 1200] will work, [10 1200] won’t). 
Attached two screen shots for visualization and after analyzing a short data stretch with otherwise identical parameters, yet specifying tlim_load = [0 60] in the first (upper example) and [1 60] in the second (below).
best,
lorenz

<img width="1065" alt="0" src="https://user-images.githubusercontent.com/60577994/74607840-86093900-50dc-11ea-9ccc-821afe92e118.PNG">
<img width="908" alt="1" src="https://user-images.githubusercontent.com/60577994/74607842-8b668380-50dc-11ea-9e1f-5dc3d49c7096.PNG">
