### ISSUE TITLE
no meta file

### ISSUE THREAD

**Issue by hennetnailo** [flatironinstitute/ironclust#42]
I am doing my recordings on an Intan system with raw data in the .rhd format, but which I used to convert into .bin for irc. I would then manually put in some of the meta data (nChan, uV/bit etc.) with the dialog as part of making the prm.
However, with irc2, I am unable to make the prm file as I need a meta file that I do not get from the intan system. I can't just write the .meta text file as there are parameters that seems to be imec or NIDQ specific or I simply don't know what they mean.

How would you advise going forward?

**Comment by jamesjun** [comment]
Thanks for your helpful feedback. I will add a support for the intan recording format such that it can acquire the meta info from the .rhd file. 

-James

**Comment by jamesjun** [comment]
Intan format is supported since v5.7.1
