### ISSUE TITLE
Function meanSubt_ is defined twice

### ISSUE THREAD

**Issue by chyumin** [flatironinstitute/ironclust#57]
I'm trying to compile ironclust to use as standalone application. But I'm getting the following error:

```
Error using compiler.internal.build.builder.Generic/build (line 81)
Error while determining required deployable files. Compilation terminated. Details:
Error using parseFile (line 13)

MATLAB code '/ironclust/matlab/irc2klusters.m' contains the following syntax error(s):
Line 513 column 22 : The current use of 'meanSubt_' is inconsistent with its previous use or definition (line 501).

Error in compiler.build.standaloneApplication (line 119)
resultsobj = builder.build;
```

The function `meanSubt_` is currently defined in [line 501](https://github.com/flatironinstitute/ironclust/blob/master/matlab/irc2klusters.m#L501) and [line 513](https://github.com/flatironinstitute/ironclust/blob/master/matlab/irc2klusters.m#L513), which one is the correct to use?

**Comment by bendichter** [comment]
@magland

**Comment by magland** [comment]
I am not familiar with how this code works. However, I would venture a guess that the second definition is what you want, because in settings where you don't get a syntax error, I believe the second would override the first.

**Comment by chyumin** [comment]
I removed the first definition and it seems to be working fine.

Thank you

**Comment by bendichter** [comment]
@chyumin great! Could you please open a draft PR with your changes so we can keep track of what adjustments you needed to make?

**Comment by chyumin** [comment]
Done! @bendichter @magland
